/* Populate tabla clientes */
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', '2018-03-06');

/*productos*/

insert into productos (nombre, precio, create_at) values ('Beef - Montreal Smoked Brisket', 56.25, '2022-09-24');
insert into productos (nombre, precio, create_at) values ('Tart - Raisin And Pecan', 56.84, '2022-03-16');
insert into productos (nombre, precio, create_at) values ('Soup - Knorr, Classic Can. Chili', 81.14, '2020-06-01');
insert into productos (nombre, precio, create_at) values ('Quail - Eggs, Fresh', 22.38, '2022-09-29');
insert into productos (nombre, precio, create_at) values ('Beets - Golden', 66.41, '2022-11-02');
insert into productos (nombre, precio, create_at) values ('Isomalt', 14.12, '2021-03-21');
insert into productos (nombre, precio, create_at) values ('Pop Shoppe Cream Soda', 15.96, '2022-09-05');
insert into productos (nombre, precio, create_at) values ('Sterno - Chafing Dish Fuel', 98.04, '2020-12-23');
insert into productos (nombre, precio, create_at) values ('Allspice - Jamaican', 96.8, '2020-09-24');
insert into productos (nombre, precio, create_at) values ('Muffin - Mix - Creme Brule 15l', 81.21, '2020-08-06');
insert into productos (nombre, precio, create_at) values ('Wine - Magnotta - Pinot Gris Sr', 93.8, '2022-12-24');
insert into productos (nombre, precio, create_at) values ('Cookies - Amaretto', 99.01, '2020-10-27');
insert into productos (nombre, precio, create_at) values ('Cornflakes', 87.61, '2022-11-23');
insert into productos (nombre, precio, create_at) values ('Sauce - Hoisin', 25.0, '2021-01-26');
insert into productos (nombre, precio, create_at) values ('Black Currants', 15.56, '2021-11-19');
insert into productos (nombre, precio, create_at) values ('Pasta - Canelloni', 48.53, '2021-05-24');
insert into productos (nombre, precio, create_at) values ('Scallops - In Shell', 19.77, '2022-09-03');
insert into productos (nombre, precio, create_at) values ('Mushroom - Chantrelle, Fresh', 85.44, '2021-12-26');
insert into productos (nombre, precio, create_at) values ('Juice - V8 Splash', 61.34, '2020-01-10');
insert into productos (nombre, precio, create_at) values ('Piping - Bags Quizna', 67.47, '2020-01-20');
insert into productos (nombre, precio, create_at) values ('Sauce - Alfredo', 27.14, '2022-06-11');
insert into productos (nombre, precio, create_at) values ('French Pastries', 86.79, '2020-01-03');
insert into productos (nombre, precio, create_at) values ('Breadfruit', 67.98, '2021-03-03');
insert into productos (nombre, precio, create_at) values ('Soup - Campbells Asian Noodle', 27.69, '2022-11-07');
insert into productos (nombre, precio, create_at) values ('Wine - Chateau Aqueria Tavel', 76.27, '2021-04-29');
insert into productos (nombre, precio, create_at) values ('Wine - Sherry Dry Sack, William', 93.45, '2020-04-13');
insert into productos (nombre, precio, create_at) values ('Potatoes - Peeled', 47.38, '2021-05-19');
insert into productos (nombre, precio, create_at) values ('Dried Peach', 62.02, '2022-05-24');
insert into productos (nombre, precio, create_at) values ('Snapple Raspberry Tea', 27.1, '2020-07-07');
insert into productos (nombre, precio, create_at) values ('Milk - Skim', 63.34, '2021-07-09');
insert into productos (nombre, precio, create_at) values ('Tomatoes - Diced, Canned', 53.37, '2022-05-31');
insert into productos (nombre, precio, create_at) values ('Wine - Magnotta - Belpaese', 32.18, '2022-06-01');
insert into productos (nombre, precio, create_at) values ('Jello - Assorted', 50.29, '2020-06-08');
insert into productos (nombre, precio, create_at) values ('The Pop Shoppe - Root Beer', 52.3, '2022-07-02');
insert into productos (nombre, precio, create_at) values ('Chicken Breast Halal', 87.3, '2022-07-15');
insert into productos (nombre, precio, create_at) values ('Apple - Royal Gala', 18.17, '2021-08-07');
insert into productos (nombre, precio, create_at) values ('Bread - Sour Sticks With Onion', 91.83, '2022-08-17');
insert into productos (nombre, precio, create_at) values ('Crackers - Trio', 60.78, '2021-07-14');
insert into productos (nombre, precio, create_at) values ('Lamb - Whole Head Off', 18.31, '2020-02-14');
insert into productos (nombre, precio, create_at) values ('Mushroom - Crimini', 39.25, '2021-08-27');
insert into productos (nombre, precio, create_at) values ('Table Cloth - 53x69 Colour', 12.79, '2021-10-23');
insert into productos (nombre, precio, create_at) values ('Wine - Red, Pinot Noir, Chateau', 23.74, '2020-11-23');
insert into productos (nombre, precio, create_at) values ('Soup - Base Broth Beef', 74.25, '2020-10-25');
insert into productos (nombre, precio, create_at) values ('Wine - Zinfandel Rosenblum', 76.45, '2020-12-20');
insert into productos (nombre, precio, create_at) values ('Wine - Dubouef Macon - Villages', 40.18, '2020-04-28');
insert into productos (nombre, precio, create_at) values ('Calypso - Black Cherry Lemonade', 26.01, '2022-05-01');
insert into productos (nombre, precio, create_at) values ('Carrots - Jumbo', 61.85, '2020-11-09');
insert into productos (nombre, precio, create_at) values ('Sugar - Splenda Sweetener', 95.07, '2021-05-05');
insert into productos (nombre, precio, create_at) values ('Beans - Soya Bean', 34.82, '2021-01-29');
insert into productos (nombre, precio, create_at) values ('Tea - Earl Grey', 69.36, '2021-01-27');
insert into productos (nombre, precio, create_at) values ('Cranberries - Fresh', 86.75, '2022-12-19');
insert into productos (nombre, precio, create_at) values ('Water - Mineral, Carbonated', 90.23, '2021-08-11');
insert into productos (nombre, precio, create_at) values ('Beer - Paulaner Hefeweisse', 75.22, '2021-08-31');
insert into productos (nombre, precio, create_at) values ('Bread - Focaccia Quarter', 57.42, '2022-07-23');
insert into productos (nombre, precio, create_at) values ('Wanton Wrap', 60.69, '2021-02-24');
insert into productos (nombre, precio, create_at) values ('Wine - Red, Wolf Blass, Yellow', 57.44, '2021-10-31');
insert into productos (nombre, precio, create_at) values ('Pastry - Baked Scones - Mini', 88.23, '2022-12-24');
insert into productos (nombre, precio, create_at) values ('Beer - Mill St Organic', 89.08, '2022-11-30');
insert into productos (nombre, precio, create_at) values ('Nantucket Apple Juice', 10.53, '2020-04-17');
insert into productos (nombre, precio, create_at) values ('Sauce - Cranberry', 69.87, '2020-07-12');
insert into productos (nombre, precio, create_at) values ('Mushroom - Oyster, Fresh', 80.31, '2021-08-14');
insert into productos (nombre, precio, create_at) values ('Spoon - Soup, Plastic', 48.63, '2021-06-21');
insert into productos (nombre, precio, create_at) values ('Bread Bowl Plain', 17.13, '2022-02-02');
insert into productos (nombre, precio, create_at) values ('Wine - Red, Metus Rose', 28.35, '2020-02-07');
insert into productos (nombre, precio, create_at) values ('Flavouring - Orange', 29.02, '2020-10-07');
insert into productos (nombre, precio, create_at) values ('Broom And Brush Rack Black', 28.76, '2020-11-19');
insert into productos (nombre, precio, create_at) values ('Doilies - 8, Paper', 74.46, '2022-08-27');
insert into productos (nombre, precio, create_at) values ('Heavy Duty Dust Pan', 86.03, '2021-08-11');
insert into productos (nombre, precio, create_at) values ('Stock - Veal, White', 17.93, '2022-03-29');
insert into productos (nombre, precio, create_at) values ('Juice - Tomato, 10 Oz', 38.75, '2020-04-30');
insert into productos (nombre, precio, create_at) values ('Fennel - Seeds', 11.79, '2020-10-03');
insert into productos (nombre, precio, create_at) values ('Apple - Fuji', 24.57, '2021-04-20');
insert into productos (nombre, precio, create_at) values ('Wine - Lou Black Shiraz', 50.06, '2020-07-09');
insert into productos (nombre, precio, create_at) values ('Sprouts - China Rose', 88.05, '2020-02-19');
insert into productos (nombre, precio, create_at) values ('Pizza Pizza Dough', 94.69, '2022-03-08');
insert into productos (nombre, precio, create_at) values ('Appetizer - Lobster Phyllo Roll', 55.93, '2022-12-10');
insert into productos (nombre, precio, create_at) values ('Crackers - Soda / Saltins', 83.42, '2021-02-05');
insert into productos (nombre, precio, create_at) values ('Lamb - Whole Head Off,nz', 26.29, '2022-11-29');
insert into productos (nombre, precio, create_at) values ('Myers Planters Punch', 43.61, '2021-07-13');
insert into productos (nombre, precio, create_at) values ('French Kiss Vanilla', 35.39, '2022-06-22');
insert into productos (nombre, precio, create_at) values ('Pork Salted Bellies', 55.45, '2021-08-12');
insert into productos (nombre, precio, create_at) values ('Muffin Batt - Ban Dream Zero', 41.25, '2020-12-11');
insert into productos (nombre, precio, create_at) values ('Lotus Rootlets - Canned', 58.75, '2022-03-10');
insert into productos (nombre, precio, create_at) values ('Crab - Soft Shell', 77.92, '2020-04-07');
insert into productos (nombre, precio, create_at) values ('Initation Crab Meat', 26.56, '2022-05-27');
insert into productos (nombre, precio, create_at) values ('Pasta - Rotini, Dry', 98.99, '2020-01-16');
insert into productos (nombre, precio, create_at) values ('Cilantro / Coriander - Fresh', 94.85, '2020-04-27');
insert into productos (nombre, precio, create_at) values ('Cheese - Victor Et Berthold', 48.79, '2022-06-26');
insert into productos (nombre, precio, create_at) values ('Beef Cheek Fresh', 74.31, '2021-10-05');
insert into productos (nombre, precio, create_at) values ('Coconut - Creamed, Pure', 77.84, '2020-06-09');
insert into productos (nombre, precio, create_at) values ('Pie Filling - Pumpkin', 66.2, '2020-01-30');
insert into productos (nombre, precio, create_at) values ('Puree - Kiwi', 94.41, '2022-01-31');
insert into productos (nombre, precio, create_at) values ('Cheese - Bakers Cream Cheese', 70.73, '2021-02-02');
insert into productos (nombre, precio, create_at) values ('Stock - Veal, White', 13.14, '2020-09-10');
insert into productos (nombre, precio, create_at) values ('Sprouts - Peppercress', 27.55, '2020-12-01');
insert into productos (nombre, precio, create_at) values ('Sambuca - Opal Nera', 11.97, '2020-01-06');
insert into productos (nombre, precio, create_at) values ('Sobe - Green Tea', 79.08, '2020-08-03');
insert into productos (nombre, precio, create_at) values ('Chinese Foods - Pepper Beef', 40.42, '2022-04-10');
insert into productos (nombre, precio, create_at) values ('Wine - Chenin Blanc K.w.v.', 83.35, '2020-10-12');
insert into productos (nombre, precio, create_at) values ('Island Oasis - Cappucino Mix', 53.0, '2020-05-16');


/*facturas*/
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Early congenital syphilis, latent', 'national', 11, '2022-11-25');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Inj unsp blood vess at abd, low back and pelvis level, init', 'policy', 10, '2020-06-12');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Fracture of one rib, left side, subs for fx w nonunion', 'approach', 1, '2020-11-10');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('3-part fracture of surgical neck of left humerus, init', 'demand-driven', 1, '2022-12-01');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Cholesteatoma of middle ear', 'functionalities', 11, '2020-08-01');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Alcohol abuse with alcohol-induced mood disorder', 'secured line', 1, '2021-09-24');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Corrosion of unsp degree of left upper arm, subs encntr', 'leading edge', 8, '2022-04-09');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Disp fx of epiphy (separation) (upper) of r femr, 7thB', 'Multi-lateral', 6, '2022-01-06');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Burn of third degree of chin, sequela', 'heuristic', 8, '2022-08-17');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Unsp injury of flexor musc/fasc/tend left thumb at forarm lv', 'Virtual', 6, '2022-11-22');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Ped on oth roll-type ped convey collid w statnry obj, sqla', 'data-warehouse', 2, '2020-01-31');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Sltr-haris Type IV physl fx low end ulna, r arm, 7thG', 'disintermediate', 11, '2022-09-22');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Disp fx of 1st metatarsal bone, r ft, 7thG', 'Business-focused', 3, '2022-07-26');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Unsp fx lower end of unsp humerus, subs for fx w delay heal', 'executive', 8, '2021-07-03');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Arthritis due to other bacteria, unspecified hand', 'local area network', 5, '2021-11-28');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Nondisp fx of epiphysis (separation) (upper) of right femur', 'conglomeration', 9, '2021-10-03');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Synovial hypertrophy, not elsewhere classified, forearm', 'directional', 4, '2022-07-11');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Other fracture of shaft of radius, unspecified arm', 'Optional', 10, '2021-03-21');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Torus fracture of lower end of left fibula, init for clos fx', 'Sharable', 1, '2021-01-13');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Malignant neoplasm of left optic nerve', 'motivating', 9, '2020-09-25');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Oth benign neoplasm skin/ left upper limb, inc shoulder', 'Proactive', 6, '2021-06-19');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Posterior subluxation of proximal end of tibia, unsp knee', 'Fully-configurable', 10, '2022-12-28');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Unsp fracture of fourth metacarpal bone, right hand, init', 'throughput', 4, '2022-02-10');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Ped on foot inj in clsn w nonmtr vehicle nontraf, sequela', 'Graphical User Interface', 3, '2021-04-20');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Nondisplaced intraarticular fracture of right calcaneus', 'forecast', 11, '2022-05-07');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Assault by other sharp object, sequela', 'Innovative', 1, '2020-09-18');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Unsp fx r forearm, subs for opn fx type 3A/B/C w routn heal', 'web-enabled', 12, '2020-01-24');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Donor of other specified organs or tissues', 'workforce', 4, '2020-10-20');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Sltr-haris Type II physeal fx phalanx of right toe, 7thB', 'circuit', 9, '2022-11-19');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Ped on rolr-skt injured in clsn w hv veh nontraf, sequela', 'Proactive', 6, '2022-09-25');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Personal history of infections of the central nervous system', 'Total', 12, '2020-12-30');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Fx unsp phalanx of l rng fngr, subs for fx w delay heal', 'static', 12, '2022-04-09');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Nondisp commnt fx unsp patella, 7thH', 'value-added', 11, '2021-05-18');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Acute lymphadenitis, unspecified', '6th generation', 4, '2023-02-12');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Poisoning by oral contraceptives, accidental, init', 'groupware', 12, '2020-09-17');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Nondisp fx of prox phalanx of l lit fngr, 7thD', 'maximized', 4, '2022-12-29');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Machinery accident on board sailboat, subsequent encounter', 'web-enabled', 2, '2021-09-25');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Poisoning by unspecified narcotics, undetermined, sequela', 'installation', 3, '2021-03-19');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Nondisp fx of prox phalanx of fngr, subs for fx w delay heal', 'Exclusive', 8, '2022-02-18');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Disp fx of dist phalanx of r great toe, 7thG', 'regional', 6, '2022-01-25');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Post disp fx of sternal end of r clavicle, init for opn fx', 'firmware', 12, '2021-03-04');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Frostbite with tissue necrosis of left hand, sequela', 'Seamless', 8, '2020-09-15');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Residual stage of angle-closure glaucoma, right eye', 'Pre-emptive', 6, '2022-07-18');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Drowning and submersion due to fall off fishing boat, init', 'fault-tolerant', 4, '2021-12-17');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Type 2 diab with mod nonp rtnop without macular edema, r eye', 'Phased', 9, '2022-12-10');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Laceration of superficial palmar arch', 'context-sensitive', 3, '2021-11-07');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Breakdown (mechanical) of other vascular grafts', 'task-force', 10, '2020-06-16');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Unspecified open wound, right ankle, sequela', 'client-driven', 3, '2020-07-12');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Underdosing of antithyroid drugs, initial encounter', 'Streamlined', 8, '2020-03-22');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Corrosion of third degree of left toe(s) (nail), subs encntr', 'Upgradable', 6, '2022-11-26');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Poisoning by other synthetic narcotics, assault', 'Automated', 6, '2022-11-01');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Lateral sublux of proximal end of tibia, right knee, sequela', 'policy', 10, '2021-11-29');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Sltr-haris Type IV physeal fx unspecified metatarsal', 'interface', 12, '2020-12-12');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Nondisp commnt fx shaft of rad, r arm, 7thD', 'moratorium', 11, '2021-03-16');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Displaced fracture of trapezoid, right wrist, sequela', 'challenge', 7, '2021-08-17');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Posterior dislocation of lens, left eye', 'model', 1, '2022-01-25');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Exposure to industr wiring, appliances and electrical mach', 'high-level', 9, '2022-02-27');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Disp fx of shaft of 2nd MC bone, l hand, 7thD', 'Public-key', 9, '2020-02-05');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Nondisp fx of intermed cuneiform of l ft, 7thP', 'Open-architected', 3, '2022-10-25');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Oth tear of unsp mensc, current injury, unsp knee, sequela', 'adapter', 1, '2021-10-26');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Dislocation of jaw, right side', 'Extended', 1, '2022-08-26');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Maternal care for anti-D [Rh] antibodies, second trimester', 'discrete', 5, '2021-03-16');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Inhalation of dry ice, subsequent encounter', 'Multi-tiered', 2, '2020-06-08');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Chronic gout due to renal impairment, left elbow, w/o tophus', 'groupware', 6, '2020-03-05');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Displ commnt fx unsp patella, 7thE', 'access', 11, '2020-05-19');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Deformity of left orbit due to trauma or surgery', 'Graphical User Interface', 7, '2023-02-14');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Juvenile rheu arthritis w systemic onset, unsp shoulder', 'De-engineered', 4, '2021-06-29');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Displ suprcndl fx w/o intrcndl extn low end l femr, 7thQ', 'projection', 3, '2021-11-28');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Mucosal cyst of postmastoidectomy cavity, bilateral ears', 'local area network', 3, '2021-11-25');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Scleritis with corneal involvement', 'budgetary management', 8, '2020-12-03');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Secondary lacrimal gland atrophy, left lacrimal gland', 'adapter', 11, '2021-10-18');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Terrorism involving dest arcrft, civilian injured, init', 'task-force', 3, '2021-07-10');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Nondisp commnt fx shaft of humer, l arm, 7thP', 'productivity', 11, '2020-05-18');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Laceration of unspecified tibial artery, right leg, sequela', 'ability', 2, '2022-10-08');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Lac w fb of abd wall, left lower q w penet perit cav, subs', 'cohesive', 2, '2022-06-23');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Other superficial bite of left thigh, subsequent encounter', 'circuit', 5, '2021-07-02');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Other lipid storage disorders', 'application', 10, '2021-10-18');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Pnctr w/o fb of unsp great toe w/o damage to nail, init', 'emulation', 2, '2021-08-12');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Displ seg fx shaft of humerus, unsp arm, init for opn fx', '3rd generation', 5, '2020-05-15');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Rupture of synovium, shoulder', 'process improvement', 1, '2022-11-19');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Other injury of inferior mesenteric artery, sequela', 'neutral', 1, '2021-11-25');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Pnctr w foreign body of r idx fngr w/o damage to nail', 'implementation', 4, '2020-01-10');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Prsn brd/alit pedl cyc injured in clsn w ped/anml, sequela', '3rd generation', 12, '2020-06-13');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Pnctr w foreign body of unsp finger w damage to nail, init', 'Visionary', 11, '2021-09-01');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Bedroom in boarding-house as place', 'global', 6, '2020-01-25');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Nondisp transverse fx shaft of humer, r arm, 7thG', 'methodical', 11, '2022-04-22');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Unil post-trauma osteoarth of first carpometacarp joint', 'Multi-channelled', 11, '2020-04-13');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Partial traumatic amputation of r low leg, level unsp, subs', 'client-server', 1, '2022-04-23');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Nondisplaced dome fracture of right talus, init for clos fx', 'heuristic', 6, '2020-08-01');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Dislocation of interphaln joint of left great toe, sequela', 'Quality-focused', 3, '2023-01-30');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Unsp inj musc/fasc/tend at shldr/up arm, unsp arm, sequela', 'well-modulated', 3, '2021-06-05');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Corrosion of first degree of right ear', 'workforce', 9, '2022-03-11');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Occup of hv veh inj pk-up truck, pk-up/van in traf, sequela', 'database', 1, '2022-05-04');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Idiopathic chronic gout, right shoulder, with tophus (tophi)', 'time-frame', 5, '2021-03-23');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Nondisp fx of hook process of hamate bone, l wrist, sequela', 'mission-critical', 6, '2020-11-05');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Laceration with foreign body of vocal cord, subs encntr', 'clear-thinking', 8, '2021-07-03');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Dislocation of proximal interphalangeal joint of thmb, init', 'real-time', 7, '2023-01-05');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Contus/lac right cerebrum w LOC of 6 hours to 24 hours, subs', 'optimal', 1, '2021-08-06');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Maternal care for fetal problem, unsp, second tri, unsp', 'Polarised', 6, '2022-05-31');
insert into facturas (descripcion, observacion, cliente_id, create_at) values ('Inj unsp blood vessel at shldr/up arm, unsp arm, sequela', 'website', 1, '2020-09-08');

/*facturas_items*/
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 39, 28);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 76, 70);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 59, 11);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 64, 45);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 16, 49);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 61, 91);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 94, 50);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 95, 90);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 83, 94);
insert into facturas_items (cantidad, factura_id, producto_id) values (1, 45, 62);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 79, 27);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 62, 18);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 15, 3);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 33, 74);
insert into facturas_items (cantidad, factura_id, producto_id) values (1, 30, 65);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 70, 20);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 67, 40);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 38, 6);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 49, 83);
insert into facturas_items (cantidad, factura_id, producto_id) values (1, 27, 90);
insert into facturas_items (cantidad, factura_id, producto_id) values (1, 97, 34);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 97, 12);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 18, 12);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 18, 80);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 72, 54);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 1, 70);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 72, 72);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 68, 25);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 70, 45);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 77, 51);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 51, 81);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 47, 23);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 19, 96);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 12, 4);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 67, 98);
insert into facturas_items (cantidad, factura_id, producto_id) values (1, 67, 47);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 7, 34);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 24, 55);
insert into facturas_items (cantidad, factura_id, producto_id) values (1, 95, 29);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 78, 26);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 19, 36);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 83, 93);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 38, 90);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 34, 36);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 8, 52);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 41, 20);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 47, 83);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 29, 87);
insert into facturas_items (cantidad, factura_id, producto_id) values (1, 64, 62);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 65, 84);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 32, 61);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 24, 95);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 83, 67);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 43, 58);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 86, 6);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 3, 14);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 56, 44);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 69, 49);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 11, 67);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 87, 36);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 93, 12);
insert into facturas_items (cantidad, factura_id, producto_id) values (1, 39, 45);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 12, 13);
insert into facturas_items (cantidad, factura_id, producto_id) values (1, 100, 58);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 29, 2);
insert into facturas_items (cantidad, factura_id, producto_id) values (1, 98, 16);
insert into facturas_items (cantidad, factura_id, producto_id) values (1, 70, 11);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 28, 55);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 42, 13);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 8, 53);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 11, 79);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 19, 64);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 13, 3);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 73, 27);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 22, 45);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 14, 49);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 69, 42);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 78, 3);
insert into facturas_items (cantidad, factura_id, producto_id) values (1, 19, 87);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 95, 39);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 86, 54);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 66, 88);
insert into facturas_items (cantidad, factura_id, producto_id) values (1, 43, 29);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 55, 13);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 6, 100);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 1, 92);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 48, 85);
insert into facturas_items (cantidad, factura_id, producto_id) values (1, 58, 96);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 95, 7);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 31, 33);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 62, 77);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 92, 65);
insert into facturas_items (cantidad, factura_id, producto_id) values (1, 36, 62);
insert into facturas_items (cantidad, factura_id, producto_id) values (4, 41, 39);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 18, 6);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 84, 56);
insert into facturas_items (cantidad, factura_id, producto_id) values (1, 86, 79);
insert into facturas_items (cantidad, factura_id, producto_id) values (1, 31, 7);
insert into facturas_items (cantidad, factura_id, producto_id) values (3, 71, 90);
insert into facturas_items (cantidad, factura_id, producto_id) values (2, 15, 55);